CREATE INDEX `idx_mustahik_organization_id` ON `mustahik` (`organization_id`);--> statement-breakpoint
CREATE INDEX `idx_mustahik_sector_id` ON `mustahik` (`sector_id`);--> statement-breakpoint
CREATE INDEX `idx_mustahik_created_at` ON `mustahik` (`created_at`);--> statement-breakpoint
CREATE INDEX `idx_mustahik_org_sector` ON `mustahik` (`organization_id`,`sector_id`);--> statement-breakpoint
CREATE INDEX `idx_mustahik_org_created` ON `mustahik` (`organization_id`,`created_at`);--> statement-breakpoint
CREATE INDEX `idx_mustahik_org_name` ON `mustahik` (`organization_id`,`name`);--> statement-breakpoint
CREATE INDEX `idx_mustahik_status_distribusi` ON `mustahik` (`status_distribusi`);--> statement-breakpoint
CREATE INDEX `idx_muzaki_organization_id` ON `muzaki` (`organization_id`);--> statement-breakpoint
CREATE INDEX `idx_muzaki_sector_id` ON `muzaki` (`sector_id`);--> statement-breakpoint
CREATE INDEX `idx_muzaki_created_at` ON `muzaki` (`created_at`);--> statement-breakpoint
CREATE INDEX `idx_muzaki_org_sector` ON `muzaki` (`organization_id`,`sector_id`);--> statement-breakpoint
CREATE INDEX `idx_muzaki_org_created` ON `muzaki` (`organization_id`,`created_at`);--> statement-breakpoint
CREATE INDEX `idx_muzaki_org_name` ON `muzaki` (`organization_id`,`name`);--> statement-breakpoint
CREATE INDEX `idx_muzaki_petugas_id` ON `muzaki` (`petugas_id`);--> statement-breakpoint
CREATE INDEX `idx_organizations_slug` ON `organizations` (`slug`);--> statement-breakpoint
CREATE INDEX `idx_organizations_is_active` ON `organizations` (`is_active`);--> statement-breakpoint
CREATE INDEX `idx_sectors_organization_id` ON `sectors` (`organization_id`);--> statement-breakpoint
CREATE INDEX `idx_sectors_is_active` ON `sectors` (`is_active`);--> statement-breakpoint
CREATE INDEX `idx_sectors_org_active` ON `sectors` (`organization_id`,`is_active`);--> statement-breakpoint
CREATE INDEX `idx_users_organization_id` ON `users` (`organization_id`);--> statement-breakpoint
CREATE INDEX `idx_users_sector_id` ON `users` (`sector_id`);--> statement-breakpoint
CREATE INDEX `idx_users_role` ON `users` (`role`);--> statement-breakpoint
CREATE INDEX `idx_users_is_active` ON `users` (`is_active`);--> statement-breakpoint
CREATE INDEX `idx_users_email_provider` ON `users` (`email`,`provider`);